-
  name: 'Paginate for Breadlesscode.Listable'
  uriPattern: '{node}<defaultUriSuffix>?<parameterName>={currentPage}'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface
  appendExceedingArguments: TRUE
