Breadlesscode:
  Listable:
    pagination:
      showSeparators: true
      showNextAndPrevious: true
      alwaysShowNextAndPrevious: false
      showFirstAndLast: true
      showFirstAndLastNumeric: false
      alwaysShowFirstAndLast: false
      numberOfLinks: 3
      labels:
        separator: '&hellip;'
        previous: '&lang;'
        next: '&rang;'
        first: '&laquo;'
        last: '&raquo;'
