Neos:
  Flow:
    mvc:
      routes:
        'Breadlesscode.Listable':
          position: 'before Neos.Neos'
          variables:
            pageSeparator: '~p'
            defaultUriSuffix: '.html'
  Neos:
    fusion:
      autoInclude:
        Breadlesscode.Listable: true
