Neos:
  Flow:
    mvc:
      routes:
        'Breadlesscode.Listable':
          position: 'before Neos.Neos'
          variables:
            paginationUriSeperator: '--page'
            defaultUriSuffix: '.html'
  Neos:
    fusion:
      autoInclude:
        Breadlesscode.Listable: true
    userInterface:
      translation:
        autoInclude:
          'Breadlesscode.Listable':
            - '*'
Breadlesscode:
  Listable:
    pagination:
      showSeperators: true
      showNextAndPrevious: true
      alwaysShowNextAndPrevious: false
      showFirstAndLast: true
      showFirstAndLastNumeric: false
      alwaysShowFirstAndLast: false
      numberOfLinks: 3
      labels:
        seperator: '&hellip;'
        previous: '&lang;'
        next: '&rang;'
        first: '&laquo;'
        last: '&raquo;'
