Neos:
  Flow:
    mvc:
      routes:
        'Breadlesscode.Listable':
          position: 'before Neos.Neos'
          variables:
            parameterName: 'page'
            defaultUriSuffix: '.html'
  Neos:
    fusion:
      autoInclude:
        Breadlesscode.Listable: true
Breadlesscode:
  Listable:
    pagination:
      showSeperators: true
      showNextAndPrevious: true
      showFirstAndLast: true
      labels:
        seperator: '&hellip;'
        previous: '&lang;'
        next: '&rang;'
        first: '&laquo;'
        last: '&raquo;'
